Repository CSCIX691DAL/general-dashboard, pull requests merged in 2021-02, with the labels that each got.

#10 password match added
  src/app/registration/registration.component.ts
Labels: enhancement

#13 Successfully refactored all html and ts files for registration.compon…
  src/app/registration/registration.component.html
  src/app/registration/registration.component.ts
Labels: Refactor

#15 Registering now stores email and password in MySQL db
  src/app/home/home.component.ts
  src/app/registration/registration.component.ts
  src/app/services/database-connection.service.ts
Labels: enhancement

#17 Error message presented upon use of existing email on registration page
  src/app/registration/registration.component.css
  src/app/registration/registration.component.html
  src/app/registration/registration.component.ts
Labels: enhancement

#22 Refactor/navbar
  proxy.conf.json
  src/app/navbar/navbar.component.css
  src/app/navbar/navbar.component.html
Labels: Refactor

#23 Signout nav element is visible upon logging in, login and register ar…
  src/app/login/login.component.ts
  src/app/navbar/navbar.component.html
Labels: enhancement

#28 Home Page Example Features in Flex Layout
  src/app/example-features/Feature.ts
  src/app/example-features/example-features.component.html
Labels: enhancement

#30 Automated Delivery
  azure-pipelines.yml
  ecosystem.config.js
  src/app/app-routing.module.ts
  src/app/auth-token.interceptor.spec.ts
  src/app/auth.service.spec.ts
  src/app/guest.guard.spec.ts
  src/app/logged-in.guard.spec.ts
  src/app/mock-auth.service.ts
  src/app/navbar/navbar.component.spec.ts
Labels: enhancement

#37 Bring dev into main for a release
  angular.json
  ecosystem.config.js
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/login/login.component.css
  src/app/login/login.component.html
  src/app/modal-basic/Report.ts
  src/app/modal-basic/modal-basic.component.css
  src/app/modal-basic/modal-basic.component.html
  src/app/modal-basic/modal-basic.component.spec.ts
  src/app/modal-basic/modal-basic.component.ts
  src/app/registration/registration.component.css
  src/app/registration/registration.component.html
  src/app/userhome/userhome.component.html
  src/assets/images/login-register-bg.png
  src/index.html
  src/polyfills.ts
  src/styles.css
Labels: release

#39 Added Message field in users.js and added Message column to Users tab…
  src/app/models/users.js
  src/app/userhome/userhome.component.html
  src/models/user.js
Labels: enhancement

#38 Removed the get users, get user Adam, etc. buttons
  src/app/home/home.component.html
  src/app/home/home.component.ts
Labels: Refactor
